apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000  # Port externe (ce sera le port d'accès)
      targetPort: 5000  # Port du conteneur
  type: LoadBalancer  # Modification ici
