apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default  # Remplace si nécessaire avec le namespace de ton choix
spec:
  selector:
    app: backend  # L'étiquette utilisée pour le déploiement backend
  ports:
    - protocol: TCP
      port: 8080          # Le port sur lequel le service est exposé à l'intérieur du cluster
      targetPort: 5000     # Le port sur lequel le conteneur écoute
  type: ClusterIP         # Type de service (par défaut c'est ClusterIP)
