apiVersion: v1
kind: Service
metadata:
  name: backend-service   # Nom du service
spec:
  selector:
    app: backend          # Sélecteur d'applications, correspond aux labels des pods du backend
  ports:
    - port: 5000          # Le port exposé par le service
      targetPort: 5000     # Le port sur lequel l'application backend écoute
  clusterIP: None         # 'ClusterIP' par défaut, mais on peut omettre cette ligne car c'est implicite
