apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000 # Port accessible depuis l'extérieur
      targetPort: 30001  # Port sur lequel ton conteneur écoute
  type: LoadBalancer  # Ou NodePort si tu veux exposer le service sur un port spécifique