apiVersion: v1
kind: Service
metadata:
  name: frontend-service  # Nom du service
spec:
  selector:
    app: frontend        # Sélecteur pour correspondre aux pods de l'application frontend
  ports:
    - port: 3000         # Le port sur lequel l'application écoute (le port du conteneur)
      targetPort: 3000    # Le port de l'application dans le conteneur
      nodePort: 30001     # Le port exposé sur les nœuds du cluster
  type: NodePort          # Définir le type du service en NodePort
