apiVersion: v1
kind: Pod
metadata:
  name: mysql-pvc
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: iboudb  # Remplacez par votre mot de passe
        - name: MYSQL_DATABASE
          value: masterdb
        - name: MYSQL_USER
          value: ibou
        - name: MYSQL_PASSWORD
          value: iboudb
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql  # Emplacement où MySQL stocke les données
  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-pvc  # Utilisation du PVC créé précédemment
