apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-deployment
  ports:
    - protocol: TCP    # Correct : utiliser 'protocol' au lieu de 'protocole'
      port: 3306        # Le port externe
      targetPort: 3306  # Le port interne du conteneur MySQL
  type: ClusterIP
