apiVersion: v1
kind: Service
metadata:
 name: mysql-service
 namespace: projetmaster
spec: 
  type: ClusterIP
  selector: 
    app: mysql-deployment
  ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306
 