apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Ajouter le mode d'accès ici
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard  # Remplace par la StorageClass de ton choix
